-- 코드를 작성해주세요
SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e 
JOIN (
    SELECT 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE,
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
ON m.YEAR = YEAR(e.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC;